name: Build image and upload it as artefact

on: 
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      imagename:
        required: true
        type: string
      platforms:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
        # first step is necessary because image names must be lowercase
      - name: set lower case image name
        run: |
          echo "IMAGE_NAME=${{ inputs.imagename }}" >>${GITHUB_ENV}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platforms }}
          tags: ${{ env.IMAGE_NAME }}
          outputs: type=tar,dest=/tmp/images
          pull: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: List files
        run: |
          tree /tmp
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.IMAGE_NAME }}
          path: /tmp/image.tar